// USER SIGN IN
export const USER_SIGN_IN_REQUEST = "USER_SIGN_IN_REQUEST";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_SIGN_IN_FAILED = "USER_SIGN_IN_FAILED";

// USER SIGN OUT
export const USER_SIGN_OUT_REQUEST = "USER_SIGN_OUT_REQUEST";
export const USER_SIGN_OUT_SUCCESS = "USER_SIGN_OUT_SUCCESS";
export const USER_SIGN_OUT_FAILED = "USER_SIGN_OUT_FAILED";

// GET_SIGNED_IN_USER_DATA
export const GET_SIGNED_IN_USER_DATA_REQUEST =
  "GET_SIGNED_IN_USER_DATA_REQUEST";
export const GET_SIGNED_IN_USER_DATA_SUCCESS =
  "GET_SIGNED_IN_USER_DATA_SUCCESS";
export const GET_SIGNED_IN_USER_DATA_FAILED = "GET_SIGNED_IN_USER_DATA_FAILED";

export const IS_LOADING = "IS_LOADING";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_ALERT = "SET_ALERT";
export const SET_QUESTIONS_LOADING = "SET_QUESTIONS_LOADING";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_FOOTER = "SET_FOOTER";
export const SET_ERROR_SHOWED = "SET_ERROR_SHOWED";
export const SET_ERROR_DURATION = "SET_ERROR_DURATION";
export const SET_ERROR_TIMER = "SET_ERROR_TIMER";
export const SET_ERROR_DURATION_TIMER = "SET_ERROR_DURATION_TIMER";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const SET_ERROR_COUNTER = "SET_ERROR_COUNTER";
export const SET_SEVERITY_STATUS = "SET_SEVERITY_STATUS";
export const SET_THEME_MODE = "SET_THEME_MODE";
export const SET_QUESTION_ARROW = "SET_QUESTION_ARROW";
export const SET_QUESTION_ARROW_TIMER = "SET_QUESTION_ARROW_TIMER";
export const SET_DISPLAYED_OPTION = "SET_DISPLAYED_OPTION";
export const SET_OPEN_DISPLAY_OPTIONS = "SET_OPEN_DISPLAY_OPTIONS";
export const SET_USER_NAME = "SET_USER_NAME";

// QUESTIONS
export const QUESTIONS_ERROR = "QUESTIONS_ERROR";
export const NEW_QUESTION_RECEIVED = "NEW_QUESTION_RECEIVED";
export const ALL_QUESTIONS_RECEIVED = "ALL_QUESTIONS_RECEIVED";
export const QUESTION_UPDATED = "QUESTION_UPDATED";
export const QUESTION_LIKES_CHANGED = "QUESTION_LIKES_CHANGED";
export const QUESTION_REMOVED = "QUESTION_REMOVED";
export const SET_EDIT_QUESTION_TEXT = "SET_EDIT_QUESTION_TEXT";
export const SET_PIN_QUESTION = "SET_PIN_QUESTION";
export const SET_UNPIN_QUESTION = "SET_UNPIN_QUESTION";

// ADMIN LOG IN
export const ADMIN_LOG_IN_REQUEST = "ADMIN_LOG_IN_REQUEST";
export const ADMIN_LOG_IN_SUCCESS = "AUTH_ADMIN_SUCCESS";
export const ADMIN_LOG_IN_FAILED = "AUTH_ADMIN_FAILED";

// USERS
export const USERS_LIST_REQUEST = "USERS_LIST_REQUEST";
export const USERS_LIST_SUCCEED = "USERS_LIST_SUCCEED";
export const USERS_LIST_FAILED = "USERS_LIST_FAILED";
export const BAN_USER_REQUEST = "BAN_USER_REQUEST";
export const BAN_USER_SUCCEED = "BAN_USER_SUCCEED";
export const BAN_USER_FAILED = "BAN_USER_FAILED";
export const SET_USERS_TAB_INDEX = "SET_USERS_TAB_INDEX";
export const SET_USER_STATUS = "SET_USER_STATUS";

// ADMIN
export const CHECK_CREDENTIALS_REQUEST = "CHECK_CREDENTIALS_REQUEST";
export const CHECK_CREDENTIALS_SUCCEED = "CHECK_CREDENTIALS_SUCCEED";
export const CHECK_CREDENTIALS_FAILED = "CHECK_CREDENTIALS_FAILED";
