export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const GET_AUTH_USER = "GET_AUTH_USER";
export const IS_LOADING = "IS_LOADING";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_ALERT = "SET_ALERT";
export const SET_QUESTIONS_LOADING = "SET_QUESTIONS_LOADING";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_FOOTER = "SET_FOOTER";
export const SET_ERROR_SHOWED = "SET_ERROR_SHOWED";
export const SET_ERROR_DURATION = "SET_ERROR_DURATION";
export const SET_ERROR_TIMER = "SET_ERROR_TIMER";
export const SET_ERROR_DURATION_TIMER = "SET_ERROR_DURATION_TIMER";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const SET_ERROR_COUNTER = "SET_ERROR_COUNTER";
export const SET_SEVERITY_STATUS = "SET_SEVERITY_STATUS";
export const GET_AUTH_USER_SUCCESS = "GET_AUTH_USER_SUCCESS";
export const GET_AUTH_USER_FAILED = "GET_AUTH_USER_FAILED";
export const SET_THEME_MODE = "SET_THEME_MODE";
export const SET_QUESTION_ARROW = "SET_QUESTION_ARROW";
export const SET_QUESTION_ARROW_TIMER = "SET_QUESTION_ARROW_TIMER";
export const SET_DISPLAYED_OPTION = "SET_DISPLAYED_OPTION";
export const SET_OPEN_DISPLAY_OPTIONS = "SET_OPEN_DISPLAY_OPTIONS";
export const SET_USER_NAME = "SET_USER_NAME";

// QUESTIONS
export const GET_LATEST_QUESTIONS = "GET_LATEST_QUESTIONS";
export const QUESTIONS_ERROR = "QUESTIONS_ERROR";
export const CHANGE_QUESTIONS_LIKES = "CHANGE_QUESTIONS_LIKES";
export const RECEIVED_QUESTION = "RECEIVED_QUESTION";
export const REMOVE_QUESTION = "REMOVE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const SET_EDIT_QUESTION_TEXT = "SET_EDIT_QUESTION_TEXT";
export const SET_PIN_QUESTION = "SET_PIN_QUESTION";
export const SET_UNPIN_QUESTION = "SET_UNPIN_QUESTION";

// ADMIN AUTH
export const AUTH_ADMIN_REQUEST = "AUTH_ADMIN_REQUEST";
export const AUTH_ADMIN_SUCCESS = "AUTH_ADMIN_SUCCESS";
export const AUTH_ADMIN_FAILED = "AUTH_ADMIN_FAILED";

// USERS
export const USERS_LIST_REQUEST = "USERS_LIST_REQUEST";
export const USERS_LIST_SUCCEED = "USERS_LIST_SUCCEED";
export const USERS_LIST_FAILED = "USERS_LIST_FAILED";
export const BAN_USER_REQUEST = "BAN_USER_REQUEST";
export const BAN_USER_SUCCEED = "BAN_USER_SUCCEED";
export const BAN_USER_FAILED = "BAN_USER_FAILED";
export const SET_USERS_TAB_INDEX = "SET_USERS_TAB_INDEX";
export const SET_USER_STATUS = "SET_USER_STATUS";

// COMMON
